/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp mce.xml -p ../dbus/src/mceInterface
 *
 * qdbusxml2cpp is Copyright (C) 2013 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "mceInterface.h"

/*
 * Implementation of interface class ComNokiaMceRequestInterface
 */

ComNokiaMceRequestInterface::ComNokiaMceRequestInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

ComNokiaMceRequestInterface::~ComNokiaMceRequestInterface()
{
}

/*
 * Implementation of interface class ComNokiaMceSignalInterface
 */

ComNokiaMceSignalInterface::ComNokiaMceSignalInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

ComNokiaMceSignalInterface::~ComNokiaMceSignalInterface()
{
}

